import { IHandbookItem } from "../types/type";

export const handbookItems: IHandbookItem[] = [
  {
    storeName: "dialyzers",
    catalogName: "Диализаторы",
    withInput: false,
    data: [
      {
        id: "1",
        name: "Диализатор1",
        category: "dialyzers",
        bigCategory: "dialyzers",
        group: "1",
      },
      {
        id: "2",
        name: "Диализатор2",
        category: "dialyzers",
        bigCategory: "dialyzers",
        group: "1",
      },
      {
        id: "3",
        name: "Диализатор3",
        category: "dialyzers",
        bigCategory: "dialyzers",
        group: "1",
      },
    ],
  },
  {
    storeName: "hubs",
    catalogName: "Концентраторы",
    withInput: true,
    data: [
      {
        id: "1",
        name: "Концентратор1",
        category: "hubs",
        bigCategory: "hubs",
        group: "1",
      },
      {
        id: "2",
        name: "Концентратор2",
        category: "hubs",
        bigCategory: "hubs",
        group: "1",
      },
    ],
  },
  {
    storeName: "catheters",
    catalogName: "Катетеры",
    withInput: false,
    data: [
      {
        id: "1",
        name: "Катетер размер1",
        category: "catheters",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "2",
        name: "Катетер размер2",
        category: "catheters",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "3",
        name: "Катетер размер3",
        category: "catheters",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "4",
        name: "Катетер размер4",
        category: "catheters",
        bigCategory: "injection",
        group: "1",
      },
    ],
  },
  {
    storeName: "cathetersType",
    catalogName: "Типы Катетеров",
    withInput: false,
    data: [
      {
        id: "1",
        name: "Катетер  Фолея",
        category: "cathetersType",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "2",
        name: "Катетер  Малеко",
        category: "cathetersType",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "3",
        name: "Катетер  Пацерра",
        category: "cathetersType",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "4",
        name: "Катетер  Тиманна",
        category: "cathetersType",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "5",
        name: "Катетер  Мелатоне",
        category: "cathetersType",
        bigCategory: "injection",
        group: "1",
      },
    ],
  },
  {
    storeName: "needles",
    catalogName: "Иглы",
    withInput: false,
    data: [
      {
        id: "1",
        name: "Игла  размер1",
        category: "needles",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "2",
        name: "Игла  размер2",
        category: "needles",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "3",
        name: "Игла  размер3",
        category: "needles",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "4",
        name: "Игла  размер4",
        category: "needles",
        bigCategory: "injection",
        group: "1",
      },
    ],
  },
  {
    storeName: "needlesType",
    catalogName: "Типы игл",
    withInput: false,
    data: [
      {
        id: "1",
        name: "Венозные",
        category: "needlesType",
        bigCategory: "injection",
        group: "1",
      },
      {
        id: "2",
        name: "Артериальные",
        category: "needlesType",
        bigCategory: "injection",
        group: "1",
      },
    ],
  },
  {
    storeName: "drugs",
    catalogName: "Лекарственные препараты",
    data: [
      {
        id: "1",
        name: "Лекарственный препарат №1",
        category: "drugs",
        bigCategory: "drugs",
        group: "2",
      },
      {
        id: "2",
        name: "Лекарственный препарат №2",
        category: "drugs",
        bigCategory: "drugs",
        group: "2",
      },
      {
        id: "3",
        name: "Лекарственный препарат №3",
        category: "drugs",
        bigCategory: "drugs",
        group: "2",
      },
    ],
  },
  {
    storeName: "drugsHome",
    catalogName: "Лекарственные препараты",
    data: [
      {
        id: "1",
        name: "Лекарственный препарат №1",
        category: "drugsHome",
        bigCategory: "drugsHome",
        group: "3",
      },
      {
        id: "2",
        name: "Лекарственный препарат №2",
        category: "drugsHome",
        bigCategory: "drugsHome",
        group: "3",
      },
      {
        id: "3",
        name: "Лекарственный препарат №3",
        category: "drugsHome",
        bigCategory: "drugsHome",
        group: "3",
      },
    ],
  },
];
